language: cpp

compiler: gcc

before_install:
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
   - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
   - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
   - sudo apt-get install debian-keyring debian-archive-keyring
   - sudo apt-key update
   - sudo apt-get update -qq
   
install:
#   - sudo pip install --upgrade pip
#   - sudo pip install cpp-coveralls
   - sudo apt-get install -qq gcc-5 g++-5
   - sudo apt-get install -qq ggcov
   - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
   - sudo apt-get install qt5-default qt5-qmake qtbase5-dev-tools qtchooser qttools5-dev qtbase5-dev libgles2-mesa-dev libqt5gui5 libqt5serialport5-dev libqt5printsupport5 libqt5widgets5 libgles2-mesa libgl1-mesa-dev libgl1-mesa-glx libglapi-mesa libegl1-mesa-dev libpango-1.0-0
   - sudo apt-get install zlib1g-dev libudev-dev
   - sudo apt-get install libgtest-dev
   - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
   
script:
   # build application
   - qmake -v
   - qmake QMAKE_CXX=g++-5 CONFIG+=debug QMAKE_CXXFLAGS+="-std=c++1y --coverage -g" QMAKE_LFLAGS+=--coverage
   - make -j4
   
   # build and run tests
   - cd tests/test
   - qmake QMAKE_CXX=g++-5 CONFIG+=debug QMAKE_CXXFLAGS+="-std=c++1y --coverage -g" QMAKE_LFLAGS+=--coverage
   - make -j4
   - ls
   - ./test
   