language: cpp

compiler: gcc

before_install:
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
   - sudo add-apt-repository -y ppa:ubuntu-sdk-team/ppa
   - sudo apt-get update -qq
   
install:
   - sudo apt-get install -qq g++-4.9
   - sudo apt-get install -qq qt5-qmake qtbase5-dev qtdeclarative5-dev libqt5webkit5-dev libsqlite3-dev
   - export CXX="g++-4.9"
   - export CXXFLAGS="-std=c++1y"
   
script:
   - qmake -qt=qt5 -v
   - qmake -qt=qt5
   - make