language: cpp

compiler: gcc

before_install:
   - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
   - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
   - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
   - sudo apt-get install debian-keyring debian-archive-keyring
   - sudo apt-key update
   - sudo apt-get update -qq
   
install:
   - sudo apt-get install -qq gcc-5 g++-5
   - sudo apt-get install -qq ggcov
   - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90
   - sudo apt-get install -qq lcov
   - gem install coveralls-lcov
   - sudo apt-get install qt5-default qt5-qmake qtbase5-dev-tools qtchooser qttools5-dev qtbase5-dev libgles2-mesa-dev libqt5gui5 libqt5serialport5-dev libqt5printsupport5 libqt5widgets5 libgles2-mesa libgl1-mesa-dev libgl1-mesa-glx libglapi-mesa libegl1-mesa-dev libpango-1.0-0
   - sudo apt-get install zlib1g-dev libudev-dev
   - sudo apt-get install libgtest-dev
   #- "cd /usr/src/gtest && sudo cmake -DCMAKE_BUILD_TYPE=RELEASE . && sudo cmake --build . && sudo mv libg* /usr/local/lib/ ; cd -"
   
script:
   # build application
   - qmake uml-tool.pro -r -spec linux-g++ CONFIG+=release
   - make -j4
   
   # build and run tests
   - cd tests/test
   - qmake test.pro -r -spec linux-g++ CONFIG+=release WITH_COV=TRUE
   - make -j4
   - ./test
   - cd ../../
   - lcov --directory . --capture --output-file coverage.info
   - lcov --remove coverage.info 'tests/*' '/usr/*' --output-file coverage.info
   - lcov --list coverage.info
   - coveralls-lcov --repo-token W5rWWqj02gOXKImGoV7l5jrWCWGe9jrtQ coverage.info
   